version: '3.0'

services:

  # MySQL service
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: my_db
      MYSQL_PASSWORD: pwd
      MYSQL_USER: user
    ports:
      - "3306:3306"
  
  # zookeeper service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"

  # Kafka service
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  # Microservice 1
  microservice1:
    image: user_management:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  # Microservice 2
  microservice2:
    image: journal_management:latest
    build:
      context: ../JournalManagement
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
